apiVersion: v1
kind: Service
metadata:
  labels:
    app: breakfast
  name: breakfast-svc
spec:
  selector:
    app: breakfast
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
